### ISSUE TITLE
ERROR <class 'urllib.error.HTTPError'>

### ISSUE THREAD

**Issue by waakanni** [EGA-archive/beacon2-ri-api#258]
This error message appears a few time in the outputs, when running the `get_descendants.py` script on the provided test dataset. Is this expected? https://github.com/EGA-archive/beacon2-ri-api/blob/master/deploy/README.md#get-descendant-and-semantic-similarity-terms

**Comment by costero-e** [comment]
Hi @waakanni ,
thank you for the report. Unfortunately, yes. The script actually only allows obolibrary or ebi family type ontologies because are the only libraries that provide .obo files that can be read by this script. This error is given when beacon finds other ontology coming from families that are not inside obolibrary or ebi.
The script could be surely improved and we are happy to receive any kind of improved code by Pull Request or suggestion by issue as beacon2 ri api is totally open source.
Thank you again for the report.
Best,
Oriol

**Comment by waakanni** [comment]
Hi @costero-e,

Thank you for the clarification. I will go ahead and close this issue for now and get back to you later if I have any better suggestions.

Best
